/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Rajdhani', 'Exo 2', 'Segoe UI', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      },
      colors: {
        'sl': {
          'bg-darkest': '#02040A',
          'bg-dark': '#0A1628',
          'bg-panel': '#0D1F3C',
          'bg-elevated': '#132744',
          'blue-deep': '#0A2463',
          'blue-primary': '#1B45D7',
          'blue-bright': '#2563EB',
          'blue-glow': '#3B82F6',
          'blue-ice': '#60A5FA',
          'blue-pale': '#93C5FD',
          'text-primary': '#F8FAFC',
          'text-secondary': '#94A3B8',
          'text-muted': '#64748B',
          'text-glow': '#E0F2FE',
          'success': '#10B981',
          'success-glow': '#34D399',
          'warning': '#F59E0B',
          'warning-glow': '#FBBF24',
          'danger': '#EF4444',
          'danger-glow': '#F87171',
          'info': '#06B6D4',
          'info-glow': '#22D3EE',
        },
        'skill': {
          'ai-engineering': '#8B5CF6',
          'ai-engineering-glow': '#A78BFA',
          'fullstack': '#3B82F6',
          'fullstack-glow': '#60A5FA',
          'design': '#EC4899',
          'design-glow': '#F472B6',
          'physical': '#10B981',
          'physical-glow': '#34D399',
          'job-hunting': '#F59E0B',
          'job-hunting-glow': '#FBBF24',
          'software-eng': '#6366F1',
          'software-eng-glow': '#818CF8',
        },
      },
      fontSize: {
        'display': '2.5rem',
        'h1': '1.75rem',
        'h2': '1.25rem',
        'h3': '1rem',
        'body': '0.9375rem',
        'small': '0.8125rem',
        'xs': '0.75rem',
        'stat': '1.5rem',
      },
    },
  },
  plugins: [],
}
